base:
  config:
    nacos:
      hostname: nacos.sad7.com
      port: 8848

# Services Versions
services:
  versions:
    search:
      v1: 1.0.0

spring:
  application:
    name: search-consumer
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

dubbo:
  scan:
    base-packages: com.sad7.myapp.plus.search.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

server:
  port: 30000